"""New Life 11

Revision ID: 87b7b2ecbb1e
Revises: 5a7300e40934
Create Date: 2020-07-18 19:50:14.910581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b7b2ecbb1e'
down_revision = '5a7300e40934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
